server:
  port: 5001
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    driverClassName: "org.postgresql.Driver"
    username: postgres
    password: "123456"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 1800 # 30 min in seconds
  refreshable-duration: 604800 # 7 days in seconds

role:
    default: facdb5cf-f3d5-4470-ad91-5f151a9e5a8b
app:
  services:
    profile: http://localhost:5002/profile
    post: http://localhost:5004/post
    file: http://localhost:5005/file
    relationship: http://localhost:5007/relationship