server:
  port: ${PORT}
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: ${DB_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION} # 30 min in seconds
  refreshable-duration: ${JWT_REFRESHABLE_DURATION} # 7 days in seconds

app:
  services:
    profile: ${PROFILE_SERVICE_URL}
    file: ${FILE_SERVICE_URL}

# Logging configuration for production
logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.tamm.identity: ${LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
